### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by brianteeman** [brianteeman/redirectplugin#3]
- [x] Make the message on redirect customisable in the plugin params
- [x] Language strings
- [ ] ~~New plugin to let a user remove their account and anonymise data = eg change name and email and id~~
- [ ] Create new custom field to use for the GDPR consent - similar to TOC field
- [ ] Package with https://github.com/brianteeman/consentnote and TOC field and ~~Removedata plugin~~

**Comment by brianteeman** [comment]
The overall idea is that this package of plugins and field will enable SIMPLE GDPR compliance - it is not intended to cover everything.

**Comment by brianteeman** [comment]
There will not be a plugin to remove or anonymise user data. This should not be automated as it will potentially effect eCommerce apps etc where you have to keep the data for legal reasons and you have to keep a record of when a user requested to be removed.

**Comment by zero-24** [comment]
> Make the message on redirect customisable in the plugin params

hmm don't be all messages customisable using language overrides? Or is there a special reason you want it to be customisable in the plugin params?

**Comment by zero-24** [comment]
>  Create new custom field to use for the GDPR consent - similar to TOC field

What do you think about https://github.com/zero-24/plg_fields_privacycheckbox

It is basically a custom checkbox field you can use in the contact form.

**Comment by brianteeman** [comment]
> hmm don't be all messages customisable using language overrides? Or is there a special reason you want it to be customisable in the plugin params?

I would prefer it to be in the plugin. It is easier to customise there than in the language overrides for the average user.

**Comment by brianteeman** [comment]
> What do you think about https://github.com/zero-24/plg_fields_privacycheckbox

Just had a look. I didnt really understand what you meant by "checkbox value". Having installed it just now I guess it is your equivalent of the title here "I consent to this information being stored"

<img width="325" alt="chrome_2018-03-09_20-33-40" src="https://user-images.githubusercontent.com/1296369/37228640-37225948-23d9-11e8-9d91-5b4273572edd.png">

**Comment by zero-24** [comment]
> Just had a look. I didnt really understand what you meant by "checkbox value". Having installed it just now I guess it is your equivalent of the title here "I consent to this information being stored"

It can look like this:

https://forum.joomla.de/core/attachment/1662-kontaktformular-datenschutz-checkbox-jpg/

Where you can add text + an a tag as value next to the checkbox. ;)

In german this is saying than:

```
I have read the <a href="/datenschutzerklaerung.htmll">data protection declaration</a>. I agree that my contact details will be stored permanently.
You can revoke your consent at any time for the future by sending an e-mail to example@example.org
```

**Comment by zero-24** [comment]
> I would prefer it to be in the plugin. It is easier to customise there than in the language overrides for the average user.

https://github.com/brianteeman/redirectplugin/pull/5 Only the strings are missing / needs to be defined.

**Comment by brianteeman** [comment]
1. Yes I understand what you mean now. I wouldn't call it "checkbox value". I would call it  something like "Information text" or "checkbox note" and then make it a textarea not a small field

**Comment by zero-24** [comment]
> Yes I understand what you mean now. I wouldn't call it "checkbox value". I would call it something like "Information text" or "checkbox note" and then make it a textarea not a small field

I have just released 1.0.2: https://github.com/zero-24/plg_fields_privacycheckbox/releases/tag/1.0.2 Thanks 👍
